###
POST http://localhost:3080/api/user HTTP/1.1
Content-Type: application/json

{"name":"Holger Danske den syvende","email":"any@mail.com","password":"FNLNexamplecom"}

###
POST http://localhost:3080/api/addressuser HTTP/1.1
Content-Type: application/json

{"name":"Helga Gargamod","email":"any4@mail.com","password":"FNLNexamplecom", "addressId":"6401bcf893414fd95f0b5772"}

### 
POST http://localhost:3080/api/address HTTP/1.1
Content-Type: application/json

{"street":"Hovedgaden 1","city":"København","zip":"1234","country":"Danmark", "addressId":"6401bcf893414fd95f0b5772"}
###
GET http://localhost:3080/api/user HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/address HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/address/6401bcf893414fd95f0b5772/users HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/userswithaddress HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3080/api/user/64004df2e39febdc72d187ad HTTP/1.1

###
PUT http://localhost:3080/api/user/6401c0a73dd8e84eff972c13 HTTP/1.1
Content-Type: application/json

{"name":"Holger Danske den 8nde","email":"somebody@mail.com","password":"passmeplease", "phone":{ "no":"12345678", "description":"mobile"}}