###
POST http://localhost:3080/login HTTP/1.1
Content-Type: application/json

{"email":"jf@mail.com","password":"JF123"}

###
POST http://localhost:3080/api/user HTTP/1.1
Content-Type: application/json

{"name":"Jesper Farekylling","email":"jf@mail.com","password":"JF123", "phone":{ "no":"12345678", "description":"mobile"}}

###
POST http://localhost:3080/api/user HTTP/1.1
Content-Type: application/json

{"name":"Fætter Højben","email":"fh@mail.com","password":"FH123", "phone":{ "no":"38889999", "description":"mobile"}, "address":{ "street":"Hovedgaden 1","city":"København","zip":"1234","country":"Danmark"}}

###
POST http://localhost:3080/api/addressuser HTTP/1.1
Content-Type: application/json

{"name":"Hulda Gargamod","email":"any5@mail.com","password":"FNLNexamplecom", "addressId":"6401bcf893414fd95f0b5772", , phone:{ "no":"12345678", "description":"mobile"}}

### 
POST http://localhost:3080/api/address HTTP/1.1
Content-Type: application/json

{"street":"Hovedgaden 1","city":"København","zip":"1234","country":"Danmark", "addressId":"6401bcf893414fd95f0b5772"}

###
GET http://localhost:3080/api/user HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/address HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/address/6401bcf893414fd95f0b5772/users HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3080/api/userswithaddress HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3080/api/user/64004df2e39febdc72d187ad HTTP/1.1

###
PUT http://localhost:3080/api/user/6401c0a73dd8e84eff972c13 HTTP/1.1
Content-Type: application/json

{"name":"Holger Danske den 8nde","email":"somebody@mail.com","password":"passmeplease", "phone":{ "no":"12345678", "description":"mobile"}}

###
GET http://localhost:3080/api/protected HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDA2MTAwMjgyMzNiNTY5ZDM5ZDMwYjYiLCJuYW1lIjoiSmVzcGVyIEZhcmVreWxsaW5nIiwiaWF0IjoxNjc4MTIxNzUyLCJleHAiOjE2NzgxMjUzNTJ9.19ZXR_GMMCDxgMZ25OymUfNCFt6mlyG2c7odgVO1FG8
